# Generated by Django 4.0 on 2021-12-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.CharField(max_length=50)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('published_datetime', models.DateTimeField()),
                ('thumbnail_url', models.TextField()),
            ],
        ),
        migrations.AddIndex(
            model_name='searchresults',
            index=models.Index(fields=['published_datetime'], name='zerver_sear_publish_2be131_idx'),
        ),
        migrations.AddIndex(
            model_name='searchresults',
            index=models.Index(fields=['ids'], name='zerver_sear_ids_5ab808_idx'),
        ),
    ]
